name: cert-manager
serviceAccountName: cert-manager-serviceaccount
values:
  applicationDependencies:
    - name: isNginxInstalled
      repository: https://gitlab.com/openlizz/applications/nginx
      shaRange: HEAD
    - name: isTreafikInstalled
      repository: https://gitlab.com/openlizz/applications/treafik
      shaRange: HEAD
  clusterValues:
    - name: nginxName1
      template: '{{ (index .Applications 0).Name }}'
    - name: nginxName2
      template: '{{ range _, $application := .Applications }} {{$application.Name}} {{ end }}'
    - name: nginxName2bis
      template: '{{ range .Applications }} {{.Name}} {{ end }}'
    - name: nginxName3
      template: '{{ range .Applications }} {{ if eq .Repository "https://gitlab.com/openlizz/applications/nginx" }} {{.Name}} {{ end }} {{- end }}'
    - name: nginxName
      template: '{{- range .Applications }} {{ if eq .Repository "https://gitlab.com/openlizz/applications/nginx" }} .Name {{ end }} {{- end }}'
    - name: treafikName
      template: '{{- range .Applications }} {{ if eq .Repository "https://gitlab.com/openlizz/applications/treafik" }} .Name {{ end }} {{- end }}'
dependencies:
  - {{ or Values.isNginxInstalled Values.isTreafikInstalled }}
dependsOn:
  {{ if Values.isNginxInstalled }}
  - name: {{ if Values.nginxName }}
    namespace: {{ if .nginxName }}
  {{ else }}
  - name: {{ if Values.treafikName }}
    namespace: {{ if Values.treafikName }}
  {{ end }}
