name: cert-manager
serviceAccountName: cert-manager-serviceaccount
values:
  applicationDependencies:
    - name: isNginxInstalled
      repository: gitlab.com/openlizz/applications/nginx
      shaRange: HEAD
    - name: isTreafikInstalled
      repository: gitlab.com/openlizz/applications/treafik
      shaRange: HEAD
  clusterValues:
    - name: nginxName
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/nginx" }}{{.Configuration.Name}}{{ end }}{{ end }}'
    - name: treafikName
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/treafik" }}{{.Configuration.Name}}{{ end }}{{ end }}'
    - name: nginxNamespace
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/nginx" }}{{.Configuration.Namespace}}{{ end }}{{ end }}'
    - name: treafikNamespace
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/treafik" }}{{.Configuration.Namespace}}{{ end }}{{ end }}'
dependencies:
  - {{ or (index . "isNginxInstalled") (index . "isTreafikInstalled") }}
dependsOn:
  {{ if (index . "isNginxInstalled") }}
  - name: {{ index . "nginxName" }}
    namespace: {{ index . "nginxNamespace" }}
  {{ else }}
  - name: {{ index . "treafikName" }}
    namespace: {{ index . "treafikNamespace" }}
  {{ end }}
