name: cert-manager
serviceAccountName: cert-manager-serviceaccount
values:
  applicationDependencies:
    - name: isNginxInstalled
      repository: https://gitlab.com/openlizz/applications/nginx
      shaRange: HEAD
    - name: isTreafikInstalled
      repository: https://gitlab.com/openlizz/applications/treafik
      shaRange: HEAD
  clusterValues:
    - name: nginxName
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "https://gitlab.com/openlizz/applications/nginx" }}{{.Name}}{{ end }}{{ end }}'
    - name: treafikName
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "https://gitlab.com/openlizz/applications/treafik" }}{{.Name}}{{ end }}{{ end }}'
dependencies:
  - {{ or (index . "isNginxInstalled") (index . "isTreafikInstalled") }}
dependsOn:
  {{ if (index . "isNginxInstalled") }}
  - name: {{ index . "nginxName" }}
    namespace: {{ index . "nginxName" }}
  {{ else }}
  - name: {{ index . "treafikName" }}
    namespace: {{ index . "treafikName" }}
  {{ end }}
