name: cert-manager
serviceAccountName: cert-manager-serviceaccount
values:
  applicationDependencies:
    - name: isNginxInstalled
      repository: https://gitlab.com/openlizz/applications/nginx
      shaRange: commitSHA1...commitSHA2
    - name: isTreafikInstalled
      repository: https://gitlab.com/openlizz/applications/treafik
      shaRange: commitSHA1...commitSHA2
  clusterValues:
    - name: nginxName
      template: '{{- range .applications }} {{ if eq .repository "https://gitlab.com/openlizz/applications/nginx" }} .name {{ end }} {{- end }}'
    - name: treafikName
      template: '{{- range .applications }} {{ if eq .repository "https://gitlab.com/openlizz/applications/treafik" }} .name {{ end }} {{- end }}'
dependencies:
  - {{ or Values.isNginxInstalled Values.isTreafikInstalled }}
dependsOn:
  {{ if Values.isNginxInstalled }}
  - name: {{ if Values.nginxName }}
    namespace: {{ if .nginxName }}
  {{ else }}
  - name: {{ if Values.treafikName }}
    namespace: {{ if Values.treafikName }}
  {{ end }}
