apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: {{ index . "namespace" }}
spec:
  serviceAccountName: cert-manager-serviceaccount
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.6.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    installCRDs: true
